### ISSUE TITLE
Todo list when Metran goes public

### ISSUE THREAD

**Issue by dbrakenhoff** [pastas/metran#2]
- [x] build documentation on readthedocs
- [x] code-style checks codacy
- [x] upload coverage codacy
- [x] add dev branch for development
- [x] add automatic PyPI release workflow
- [x] make first release

**Comment by dbrakenhoff** [comment]
Closed by #4
